service: serverless-offline-aws

frameworkVersion: ">=1.20.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-1
  memorySize: 128
  timeoue: 6
  versionFunctions: true

  environment:
    MAILGUN_API_KEY:

package:
  individually: true
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

custom:
  webpackIncludeModules: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

functions:
  test:
    handler: src/index.test
    events:
      - http:
          path: /test
          method: get
